#!/usr/bin/env node
// Fetches all F-chapter and Z-chapter ICD-10-CM codes from the NIH Clinical
// Tables API and writes them to src/shared/icd10-codes.ts.
//
// Run: node scripts/fetch-icd10.mjs
//
// Source: https://clinicaltables.nlm.nih.gov/apidoc/icd10cm/v3/doc.html
// Data is public-domain (CMS / NCHS via NIH/NLM).

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../src/shared/icd10-codes.ts')
const ENDPOINT = 'https://clinicaltables.nlm.nih.gov/api/icd10cm/v3/search'
const PAGE_SIZE = 500

async function fetchChapter(prefix) {
  const out = []
  let offset = 0
  while (true) {
    const url = `${ENDPOINT}?sf=code&terms=${prefix}&maxList=${PAGE_SIZE}&offset=${offset}`
    const res = await fetch(url)
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`)
    const data = await res.json()
    const total = data[0]
    const rows = data[3] // [[code, description], ...]
    for (const [code, description] of rows) {
      if (!code.startsWith(prefix)) continue
      out.push({ code, description })
    }
    offset += rows.length
    if (offset >= total || rows.length === 0) break
  }
  return out
}

function tsLiteral(s) {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

const f = await fetchChapter('F')
const z = await fetchChapter('Z')
const all = [...f, ...z].sort((a, b) => a.code.localeCompare(b.code))

const banner = `// AUTO-GENERATED by scripts/fetch-icd10.mjs — do not edit by hand.
// Source: NIH/NLM Clinical Tables API (ICD-10-CM, public domain).
// Scope: chapter F (mental, behavioral, neurodevelopmental) + chapter Z
// (factors influencing health status). Regenerate annually after CMS update.
`

const body = `export interface Icd10Code {
  code: string
  description: string
}

export const ICD10_CODES: readonly Icd10Code[] = [
${all.map((c) => `  { code: ${tsLiteral(c.code)}, description: ${tsLiteral(c.description)} }`).join(',\n')}
]
`

writeFileSync(OUT, banner + '\n' + body)
console.log(`wrote ${all.length} codes (${f.length} F + ${z.length} Z) to ${OUT}`)
