/**
 * Google Drive — export session notes as formatted Google Docs.
 *
 * Flow:
 * 1. Ensure an "EHR Buddy Notes" folder exists in Drive
 * 2. Create a Google Doc with formatted content
 * 3. Return the doc ID (stored on the session row)
 */

import { google } from 'googleapis'
import { getAuthClient, isConnected } from './auth'
import { getDb } from '../db/connection'

const FOLDER_NAME = 'EHR Buddy Notes'

/**
 * Get or create the "EHR Buddy Notes" folder in Drive.
 */
async function ensureFolder(auth: InstanceType<typeof google.auth.OAuth2>): Promise<string> {
  const db = getDb()

  // Check stored folder ID
  const row = db.prepare("SELECT value FROM app_meta WHERE key = 'google_notes_folder_id'").get() as
    | { value: string }
    | undefined

  if (row?.value) {
    // Verify it still exists
    const drive = google.drive({ version: 'v3', auth })
    try {
      const res = await drive.files.get({ fileId: row.value, fields: 'id,trashed' })
      if (!res.data.trashed) return row.value
    } catch {
      // Folder was deleted — recreate
    }
    db.prepare("DELETE FROM app_meta WHERE key = 'google_notes_folder_id'").run()
  }

  // Create folder
  const drive = google.drive({ version: 'v3', auth })
  const res = await drive.files.create({
    requestBody: {
      name: FOLDER_NAME,
      mimeType: 'application/vnd.google-apps.folder'
    },
    fields: 'id'
  })

  const folderId = res.data.id!
  db.prepare(
    "INSERT OR REPLACE INTO app_meta (key, value) VALUES ('google_notes_folder_id', ?)"
  ).run(folderId)

  return folderId
}

export interface NoteExportInput {
  clinicianName: string
  clinicianCredentials: string | null
  clientName: string
  clientDob: string | null
  sessionDate: string
  startTime: string
  endTime: string
  cptCode: string
  icd10Codes: string | null
  feeCents: number
  noteFormat: 'DAP' | 'FREE'
  noteBody: string | null
}

/**
 * Export a session note as a Google Doc.
 * Returns the doc ID.
 */
export async function exportNoteToDoc(input: NoteExportInput): Promise<string | null> {
  if (!isConnected()) throw new Error('Not connected to Google')

  const auth = getAuthClient()
  const folderId = await ensureFolder(auth)
  const docs = google.docs({ version: 'v1', auth })
  const drive = google.drive({ version: 'v3', auth })

  const title = `${input.clientName} — Session Note — ${input.sessionDate}`

  // 1. Create empty doc
  const createRes = await drive.files.create({
    requestBody: {
      name: title,
      mimeType: 'application/vnd.google-apps.document',
      parents: [folderId]
    },
    fields: 'id'
  })

  const docId = createRes.data.id!

  // 2. Build formatted content via batchUpdate
  const requests: any[] = []
  let idx = 1 // docs start at index 1

  function insertText(text: string, bold = false, fontSize?: number): void {
    const endIdx = idx + text.length
    requests.push({ insertText: { location: { index: idx }, text } })
    if (bold || fontSize) {
      const style: any = {}
      const fields: string[] = []
      if (bold) { style.bold = true; fields.push('bold') }
      if (fontSize) { style.fontSize = { magnitude: fontSize, unit: 'PT' }; fields.push('fontSize') }
      requests.push({
        updateTextStyle: {
          range: { startIndex: idx, endIndex: endIdx },
          textStyle: style,
          fields: fields.join(',')
        }
      })
    }
    idx = endIdx
  }

  function insertLine(): void {
    insertText('\n')
  }

  // Header
  const creds = input.clinicianCredentials ? `, ${input.clinicianCredentials}` : ''
  insertText(`${input.clinicianName}${creds}\n`, true, 14)
  insertLine()

  // Client info
  insertText('Client: ', true)
  insertText(`${input.clientName}`)
  if (input.clientDob) insertText(` (DOB: ${input.clientDob})`)
  insertLine()
  insertLine()

  // Session details
  insertText('Session Details\n', true, 12)
  insertText(`Date: ${input.sessionDate}\n`)
  insertText(`Time: ${input.startTime} – ${input.endTime}\n`)
  insertText(`CPT Code: ${input.cptCode}\n`)
  if (input.icd10Codes) insertText(`ICD-10: ${input.icd10Codes}\n`)
  insertText(`Fee: $${(input.feeCents / 100).toFixed(2)}\n`)
  insertLine()

  // Note
  insertText('Session Note\n', true, 12)
  if (input.noteBody) {
    insertText(input.noteBody)
    insertLine()
  } else {
    insertText('(No note recorded)\n')
  }
  insertLine()

  // Footer
  insertText('— Generated by EHR Buddy', false, 9)
  insertLine()

  await docs.documents.batchUpdate({ documentId: docId, requestBody: { requests } })

  return docId
}
